[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
serviceName = "binance-ama-tgbot"

[services.variables]
NODE_ENV = "production"